title: "Martín Arnaiz Iglesias"
description: "Mi página personal"
url: "https://tu-usuario.github.io"
author:
  name: "Martín Arnaiz Iglesias"
  bio: "PhD Student at Université Paris Cité"
  links:
    - label: "GitHub"
      url: "https://github.com/tu-usuario"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/tu-usuario"
